#!/usr/bin/env bash
#provide the path to the file to transfer
#provide the IP address of the server
#provide the username
#provide the ssh private key scp used

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi