#!/usr/bin/env bash

#install nginx and configure it
#nginx replies with a Hellow World string on a curl request

sudo apt update
sudo apt install nginx -y

echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/listen\ \[::\]:80\ default_server;/listen\ 80\ default_server;/' /etc/nginx/sites-available/default

sudo nginx -t
sudo nginx -s stop
sudo nginx