#!/usr/bin/env bash
#install haproxy v2.4
#enable management via init script
#using round robbin distribution algorithm for traffics

apt-get install haproxy
apt-get update

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    maxconn 2000
    daemon

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    frontend http-in
        bind *:80
        default_backend webservers

    backend webservers
        balance roundrobin
        server 205618-web-01 54.237.85.142:80 check
        server 205618-web-02 54.160.79.143:80 check

" >> /etc/haproxy/haproxy.cfg

service haproxy start