#!/usr/bin/env bash
#fizzbuzz

num=1
for ((num=1; num <= 100; num+=1)); do
	if (( num % 5 == 0 && num % 3 == 0 )); then
		echo "FizzBuzz"
	elif (( num % 3 == 0 )); then
		echo "Fizz"
	elif (( num % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$num"
	fi
done
