#!/usr/bin/env bash
#configure my firewall

sudo apt-get install ufw -y
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw allow in 22/tcp
sudo ufw allow in 443/tcp
sudo ufw allow in 80/tcp
